# Generated by Django 5.1.1 on 2024-09-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_github', '0002_githubrepository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepository',
            old_name='retrievd_at',
            new_name='retrieved_at',
        ),
    ]
