# Generated by Django 5.1.1 on 2024-09-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_github', '0003_rename_retrievd_at_githubrepository_retrieved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
