# Generated by Django 5.1.1 on 2024-09-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_github', '0004_githubrepository_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
